"""Pinned in-package subset; external registry conformance is not asserted."""
CORE_RELEASE_ID = 'MG-RL-13.0-20260926-RELEASE-I'
PIN_MANIFEST_SHA256 = 'b8ec26e3cac39c73ea513eee6ffa8737cb88a4efde44fda2bb3e0d1ae55a2357'
STAGES = {'rg': ['RG_SUPPORTED', 'RG_NARROWED', 'RG_REFUSED'], 'rf_ncrc': ['RF_PASS', 'RF_FAIL', 'RF_ESCALATE', 'NCRC_UNKNOWN'], 'trc': ['TRC_PASS', 'TRC_NOT_TRIGGERED', 'TRC_FAIL', 'TRC_ESCALATE'], 'csv': ['CSV_PASS', 'CSV_PASS_WITH_CONTROLS', 'CSV_NOT_MATERIAL', 'CSV_FAIL', 'CSV_REDESIGN_REQUIRED', 'CSV_ESCALATE', 'CSV_EMERGENCY_PROVISIONAL']}
FRAMEWORK_VERDICTS = ['BLOCK', 'REFUSE_DETERMINISTIC_SELECTION', 'ALLOW_FRAMEWORK_SELECTION', 'ESCALATE']
DECISION_STATES = ['SELECTED_DECISIVE', 'SELECTED_BY_AUTHORITY_NON_DECISIVE', 'PROVISIONAL_WITH_CONTROLS', 'DELAY', 'REDESIGN', 'ESCALATE', 'REFUSE', 'NO_SELECTABLE_OPTION', 'EMERGENCY_PROVISIONAL']
EXECUTION_STATES = ['NOT_AUTHORIZED', 'AUTHORIZED_WITHIN_SCOPE', 'EXECUTION_BLOCKED', 'EXECUTED_UNDER_MONITORING']
